language:
- python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: y6jU5Y9Xene6VMsjlNDd2fztAXsQLEhtnXOaTomvpxEiS/Avq3NfhynqI7E+DOA8Y22i5FAFT6amL747lCRH0ll85/hwvClEH/+2oNhHjiw0tzE78WaoC1r2HLiM+dWvaRYgfMa0jVYt+7HnLWCrc4ybmn0w90vNFf8DOP5ovHnN7E7ebEDaELtkGhVW/cHmfIYBNQ9s+H1WQFCsMr7BL36Bun3Ca06HNQEM/EQlsqv+Yy8lR/KYedqo+lWs3l3U2Fsc3KASd1sBElhAB6K69ekAyYbqdAzrP7CB8P0RA99zVba4yBiQJk3+XYNznasAfqGj7U56jp6wYt6dbO5ooRgz2zAa7/0whA+X1e6zBHJYFWm2JkS8VnG8naGvsTEuJrhA9cUT2ludSm9ztiLXM0KYjBu5nlrw8k/AzjAj+oBP58+ltZE0pHbf1YFWhD9HOEo+r7RYaf8agW6Gf52zkkHaCzuYklP+hs+oYjdS4PwgHjRgNl8BcZiQ/ysuy3WN4Gj5t2bVCOa6Zp7MXh0cvH2EZgWi9dg3G5aIlfkU6XfFMlvB7YddHkEYr2IXbvV8XmWlEdcpqTPMmLZAUUgPEb9Hkwv/Xyv+q5mQVxEB04uc07plWH4yFH6D9+y9PzLlsbjavWNoQWUZDvMeEdUBoDQzqK2kJBNII+v6m3FJ8JQ=
  app: polar-badlands-35773
  on:
    repo: MaciejSwierad/Flashcards
