DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS flashcards;

CREATE TABLE users(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE flashcards(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  answer TEXT NOT NULL,
  category TEXT NOT NULL,
  LEVEL INTEGER NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id)
)